version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j
  frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"
      - "7687:7687"
